Test Written for compound assignment operator (+=,-=)
RasmusBroborg/dotnet-timecode pull request #51
Opened 2022-11-02 18:40 UTC by hiteshbhavsar

Hello @RasmusBroborg, I have made written the test required for the compound assignment operator += and -=. I request you review them and let me know if there are any changes that are required.

Best Regards.
Hitesh

2022-11-02 20:26 UTC, RasmusBroborg requested changes
@hiteshbhavsar  Thank you for submitting test cases which verify the integrity of the Timecode class. 

I have spotted two lines which need to be revised before the Pull Request can be accepted.

Best,
Rasmus

2022-11-02 20:26 UTC, RasmusBroborg commented on tests/timecode.test/Timecode_Test.cs
> +      Assert.Equal(10, t2.Second);
This should be t1.Second

2022-11-02 20:26 UTC, RasmusBroborg commented on tests/timecode.test/Timecode_Test.cs
> +      Assert.Equal(12, t2.Second);
This should be t1.Second

2022-11-03 03:49 UTC, hiteshbhavsar commented on tests/timecode.test/Timecode_Test.cs
> +      Assert.Equal(10, t2.Second);
Thank you for letting me know that.

2022-11-03 03:49 UTC, hiteshbhavsar commented on tests/timecode.test/Timecode_Test.cs
> +      Assert.Equal(12, t2.Second);
Thank you for letting me know that.

2022-11-03 06:55 UTC, RasmusBroborg approved these changes
Hi @hiteshbhavsar,
Your additions look great and all tests have passed their checks, confirming your theory. I will approve the PR and merge with main. 

This PR closes #47.

2022-11-03 06:56 UTC, merged